# Generated by Django 5.1.7 on 2025-04-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=15)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=1500)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf_app.slot')),
            ],
        ),
    ]
