# Generated by Django 5.1.7 on 2025-04-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
